import {useEffect,useMemo,useState} from 'react';
import {combatAssets,type CombatActor} from './combatAssets';
export default function AnimationPreview(){
 const [actor,setActor]=useState<CombatActor>('warrior'),[action,setAction]=useState('idle'),[frame,setFrame]=useState(0),[playing,setPlaying]=useState(true),[speed,setSpeed]=useState(1),[bg,setBg]=useState('dark'),[guides,setGuides]=useState(true),[direction,setDirection]=useState('left');
 const actions=Object.keys(combatAssets[actor].actions);const data=useMemo(()=>combatAssets[actor].actions[action as keyof typeof combatAssets[typeof actor]['actions']]||combatAssets[actor].actions[actions[0] as keyof typeof combatAssets[typeof actor]['actions']], [actor,action,actions]);
 useEffect(()=>{if(!actions.includes(action))setAction(actions[0]);setFrame(0);},[actor]);
 useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setFrame(f=>(f+1)%data.frames),Math.max(16,1000/data.fps/speed));return()=>window.clearInterval(id);},[playing,data,speed]);
 const bgClass=bg==='light'?'preview-light':bg==='forest'?'preview-forest':'preview-dark';
 return <main className="animation-preview"><header><span className="eyebrow">DEV · PRÉVIA DE ANIMAÇÕES</span><h1>Folhas de combate</h1><p>Prévia no tamanho lógico usado na caça. A prévia não altera o estado do jogo.</p></header><section className={`preview-stage ${bgClass} ${guides?'with-guides':''}`}><div className="preview-ground"/><div className="preview-sprite" style={{backgroundImage:`url(${data.file})`,backgroundSize:`${combatAssets[actor].cell.width*data.frames}px ${combatAssets[actor].cell.height}px`,backgroundPosition:`-${frame*combatAssets[actor].cell.width}px 0`,transform:`scale(${direction==='right'?-1.05:1.05},1.05)`}}/><span className="preview-frame">quadro {frame+1}/{data.frames}</span></section><section className="preview-controls"><label>Ator<select value={actor} onChange={e=>setActor(e.target.value as CombatActor)}><option value="warrior">Guerreiro</option><option value="bat">Morcego sombrio</option></select></label><label>Ação<select value={action} onChange={e=>{setAction(e.target.value);setFrame(0)}}>{actions.map(a=><option key={a}>{a}</option>)}</select></label><label>Direção<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="left">Esquerda</option><option value="right">Direita (espelho)</option></select></label><label>Velocidade<select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="0.5">0,5×</option><option value="1">1×</option><option value="1.5">1,5×</option><option value="2">2×</option></select></label><div className="preview-buttons"><button onClick={()=>setPlaying(v=>!v)}>{playing?'Pausar':'Reproduzir'}</button><button onClick={()=>setFrame(f=>(f+1)%data.frames)}>Avançar quadro</button><button onClick={()=>setFrame(0)}>Reiniciar</button></div><label>Fundo<select value={bg} onChange={e=>setBg(e.target.value)}><option value="dark">Escuro</option><option value="light">Claro</option><option value="forest">Bosque</option></select></label><label className="check"><input type="checkbox" checked={guides} onChange={e=>setGuides(e.target.checked)}/> célula, pivô e chão</label></section></main>;
}
