export type CombatAction={file:string;frames:number;fps:number;durationMs:number;loop:boolean;cell?:{width:number;height:number};pivotY?:number;pivotX?:number;impact?:{x:number;y:number};impactFrame?:number};
export type CombatActorMetadata={id:string;label:string;cell:{width:number;height:number};pivot:{x:number;y:number};anchors:{feet:{x:number;y:number};shadow:{x:number;y:number};impact?:{x:number;y:number}};source:string;license:string;actions:Record<string,CombatAction>;directions:readonly string[]};
// PixelLab sheets use 192x192 cells with feet at y=172 (assets/tools/gpt_sprite_pipeline.py).
const pixellabCell={width:192,height:192};
const cell={width:112,height:144},pivot={x:.5,y:.88},anchors={feet:{x:.5,y:.88},shadow:{x:.5,y:.96}};
export const combatAssets:Record<string,CombatActorMetadata>={
 warrior:{id:'cryptidle.warrior.forest.v1',label:'Guerreiro',cell,pivot,anchors,source:'idle/walk/attack: PixelLab, owner-approved model (assets/characters/warrior); other actions: assets/generate_detailed_sprites.py procedural fallback',license:'Original project asset; final license decision belongs to owner',actions:{idle:{file:'/art/warrior-v2-idle.png',frames:4,fps:5,durationMs:800,loop:true,cell:pixellabCell,pivotY:172/192},walk:{file:'/art/warrior-v2-walk.png',frames:8,fps:10,durationMs:800,loop:true,cell:pixellabCell,pivotY:172/192},attack:{file:'/art/warrior-v2-attack.png',frames:5,fps:8,durationMs:630,loop:false,impact:{x:.94,y:.42},impactFrame:2,cell:{width:224,height:192},pivotX:96/224,pivotY:172/192},skill:{file:'/art/warrior-forest-skill.png',frames:6,fps:10,durationMs:600,loop:false,impact:{x:.82,y:.4},impactFrame:3},hurt:{file:'/art/warrior-forest-hurt.png',frames:3,fps:8,durationMs:375,loop:false},death:{file:'/art/warrior-forest-death.png',frames:6,fps:7,durationMs:857,loop:false}},directions:['left','right']},
 bat:{id:'cryptidle.bat.forest.v1',label:'Morcego sombrio',cell,pivot,anchors,source:'assets/generate_detailed_sprites.py; original deterministic Pillow pixel drawings',license:'Original project asset; final license decision belongs to owner',actions:{idle:{file:'/art/bat-forest-idle.png',frames:6,fps:6,durationMs:1000,loop:true},move:{file:'/art/bat-forest-move.png',frames:6,fps:8,durationMs:750,loop:true},attack:{file:'/art/bat-forest-attack.png',frames:6,fps:10,durationMs:600,loop:false,impact:{x:.75,y:.5},impactFrame:3},hurt:{file:'/art/bat-forest-hurt.png',frames:3,fps:8,durationMs:375,loop:false},death:{file:'/art/bat-forest-death.png',frames:6,fps:7,durationMs:857,loop:false}},directions:['left','right']}
};
export type CombatActor=keyof typeof combatAssets;
