import {useEffect,useRef} from 'react';
import Phaser from 'phaser';
import type {GameState,PlayerPresence,RegionDefinition,SkillDefinition} from '@cryptidle/shared';
import {combatAssets,type CombatAction} from './combatAssets';
type Props={state:GameState;players:PlayerPresence[];regions:RegionDefinition[];skills:SkillDefinition[]};
const forestAssets=new Set(['forest-warrior','forest-rat','forest-slime','forest-bat']);
// The approved Warrior sheet (skin 0) is used everywhere; other classes/skins keep their original sprites.
const spriteKey=(classId:string,skin:number)=>classId==='warrior'&&skin===0?'warrior-forest':`${classId}-${skin}`;
const combatSheets:Record<string,string[]>={
 'warrior-forest':['idle','walk','attack','skill','hurt','death'],
 'bat-forest':['idle','move','attack','hurt','death']
};
export default function World(props:Props){
 const host=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;
 useEffect(()=>{
  class WorldScene extends Phaser.Scene{
   backdrop!:Phaser.GameObjects.Image;actors:Phaser.GameObjects.GameObject[]=[];signature='';hero?:Phaser.GameObjects.Sprite;foe?:Phaser.GameObjects.Sprite;encounterKey='';seenHp:number|undefined;lastHeroHp:number|undefined;status?:Phaser.GameObjects.Text;lastStateTime=0;hydrated=false;
   reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
   preload(){for(const k of ['town','forest','crypt','citadel'])this.load.image(k,`/art/${k}.png`);for(const cls of ['warrior','mage','priest'])for(const skin of [0,1])this.load.spritesheet(`${cls}-${skin}`,`/art/${cls}-${skin}.png`,{frameWidth:32,frameHeight:48});for(let i=0;i<10;i++)this.load.spritesheet(`monster-${i}`,`/art/monster-${i}.png`,{frameWidth:32,frameHeight:48});for(const key of forestAssets)this.load.spritesheet(key,`/art/${key}.png`,{frameWidth:160,frameHeight:112});for(const [key,actions] of Object.entries(combatSheets)){const metadata=key==='warrior-forest'?combatAssets.warrior:combatAssets.bat;const sheet=(action:string)=>{const data=metadata.actions[action as keyof typeof metadata.actions] as CombatAction,size=data.cell||metadata.cell;return [data.file,{frameWidth:size.width,frameHeight:size.height}] as const;};this.load.spritesheet(key,...sheet('idle'));for(const action of actions)this.load.spritesheet(`${key}-${action}`,...sheet(action));}}
   create(){this.backdrop=this.add.image(480,300,'town').setDisplaySize(960,640);for(const key of [...['warrior','mage','priest'].flatMap(c=>[`${c}-0`,`${c}-1`]),...Array.from({length:10},(_,i)=>`monster-${i}`),...forestAssets]){const special=forestAssets.has(key),actions=special?[['idle',0,1,3],['move',0,1,7],['attack',2,3,10],['death',3,3,5]] as const:[['idle',0,2,4],['move',3,5,5],['attack',6,8,9],['death',9,11,5]] as const;for(const [action,start,end,rate] of actions)this.anims.create({key:`${key}-${action}`,frames:this.anims.generateFrameNumbers(key,{start,end}),frameRate:rate,repeat:action==='death'?0:-1});}for(const [key,actions] of Object.entries(combatSheets)){const metadata=key==='warrior-forest'?combatAssets.warrior:combatAssets.bat;for(const action of actions){const data=metadata.actions[action];this.anims.create({key:`${key}-${action}`,frames:this.anims.generateFrameNumbers(`${key}-${action}`,{start:0,end:data.frames-1}),frameRate:data.fps,repeat:data.loop?-1:0});}}this.status=this.add.text(480,152,'',{fontFamily:'Inter,system-ui',fontSize:'18px',color:'#f1dfb4',stroke:'#101817',strokeThickness:5}).setOrigin(.5).setAlpha(0);}
   animate(sprite:Phaser.GameObjects.Sprite,action:string){// Playing an action swaps the texture, so resolve animations from the actor's base key.
   const key=(sprite.getData('actor') as string|undefined)||sprite.texture.key,actual=key==='warrior-forest'&&action==='move'?'walk':action,animation=`${key}-${actual}`;if(!this.anims.exists(animation))return;sprite.play(animation);const meta=key==='warrior-forest'?combatAssets.warrior:key==='bat-forest'?combatAssets.bat:null;const data=meta?.actions[actual as keyof typeof meta.actions] as CombatAction|undefined;if(data)sprite.setOrigin(.5,data.pivotY??.88);}
   actor(x:number,y:number,key:string,label:string,scale=3){const detailed=Object.prototype.hasOwnProperty.call(combatSheets,key);const special=forestAssets.has(key);const shadow=this.add.ellipse(x,y+7,detailed?118:special?108:68,detailed?18:special?16:18,0x05080a,.48);const s=this.add.sprite(x,y,key).setData('actor',key).setOrigin(.5,detailed&&key==='warrior-forest'?(combatAssets.warrior.actions.idle as CombatAction).pivotY??.88:.88).setScale(detailed?1.05:scale).play(`${key}-idle`);const t=this.add.text(x,y+(detailed?76:36),label,{fontFamily:'Georgia',fontSize:'17px',color:'#f1e7cf',stroke:'#101718',strokeThickness:5}).setOrigin(.5);this.actors.push(shadow,s,t);return s;}
   float(x:number,y:number,text:string,color:string){const t=this.add.text(x,y,text,{fontSize:'23px',fontFamily:'Georgia',color,stroke:'#111a1e',strokeThickness:5}).setOrigin(.5);if(this.reducedMotion)this.time.delayedCall(900,()=>t.destroy());else this.tweens.add({targets:t,y:y-42,alpha:0,duration:1000,onComplete:()=>t.destroy()});}
   announce(text:string){if(!this.status)return;this.status.setText(text).setAlpha(1);this.tweens.killTweensOf(this.status);if(this.reducedMotion)this.time.delayedCall(1200,()=>this.status?.setAlpha(0));else this.tweens.add({targets:this.status,alpha:0,delay:1000,duration:450});}
   newEncounter(){const {state,regions,skills}=latest.current,c=state.character;if(!c?.encounter||!this.foe||!this.hero)return;this.encounterKey=`${c.encounter.sequence}:${c.encounter.monsterId}`;this.seenHp=c.encounter.monsterHp;if(this.reducedMotion)this.foe.setAlpha(1).setY(385);else{this.foe.setAlpha(0).setY(350);this.tweens.add({targets:this.foe,alpha:1,y:385,duration:420,ease:'Sine.Out'});}if(this.reducedMotion)this.animate(this.hero,'idle');else{this.animate(this.hero,'move');this.tweens.add({targets:this.hero,x:405,duration:300,yoyo:true,ease:'Sine.InOut',onComplete:()=>{if(this.hero?.active)this.animate(this.hero,'idle');}});}const monster=regions.find(r=>r.id===c.regionId)?.monsters.find(m=>m.id===c.encounter?.monsterId),active=skills.filter(skill=>skill.classId===c.classId&&c.skills.includes(skill.id));this.announce(monster?`${monster.name} surgiu`:'Novo encontro');if(active.length)this.float(this.hero.x,this.hero.y-108,active.map(skill=>skill.name).join(' · '),'#d9c78d');}
    update(){const {state,players,regions}=latest.current,c=state.character;if(!c)return;const initialLoad=!this.hydrated,boss=state.room?.status==='running',r=regions.findIndex(x=>x.id===c.regionId),monster=regions[r]?.monsters.find(x=>x.id===c.encounter?.monsterId),plainFoe=boss?'monster-9':r>=0?`monster-${r*3+Math.max(0,regions[r].monsters.findIndex(x=>x.id===c.encounter?.monsterId))}`:'',foeKey=r===0?({rat:'forest-rat',slime:'forest-slime',bat:'bat-forest'}[monster?.id||'']||plainFoe):plainFoe,heroKey=spriteKey(c.classId,c.skin);const sig=JSON.stringify([c.classId,c.skin,c.regionId,boss,heroKey,players.filter(p=>!p.regionId).map(p=>[p.id,p.skin]),state.room?.members.map(m=>m.characterId)]);
    if(sig!==this.signature){this.signature=sig;this.actors.forEach(a=>a.destroy());this.actors=[];this.backdrop.setTexture(boss?'citadel':r<0?'town':['forest','crypt','citadel'][r]||'forest');this.hero=this.actor(r<0&&!boss?470:350,390,heroKey,c.name,forestAssets.has(heroKey)?1:3);this.foe=undefined;this.encounterKey='';this.seenHp=undefined;if(boss)this.foe=this.actor(660,370,'monster-9','Guardião do Eclipse',5);else if(r>=0){const flying=monster?.id==='bat';this.foe=this.actor(655,flying?330:385,foeKey,monster?.name||'Criatura',forestAssets.has(foeKey)?1:3.5);if(flying&&!this.reducedMotion)this.tweens.add({targets:this.foe,y:318,yoyo:true,repeat:-1,duration:1250,ease:'Sine.InOut'});}else players.filter(p=>p.id!==c.id&&!p.regionId).slice(0,8).forEach((p,i)=>{const s=this.actor(230+(i%4)*145,310+Math.floor(i/4)*140,spriteKey(p.classId,p.skin),p.name,2.4);if(!this.reducedMotion){this.animate(s,'move');this.tweens.add({targets:s,x:s.x+12,yoyo:true,repeat:-1,duration:2800+i*140});}});}
    if(r>=0&&c.encounter&&this.foe){const key=`${c.encounter.sequence}:${c.encounter.monsterId}`;if(this.encounterKey!==key){if(initialLoad){this.encounterKey=key;this.seenHp=c.encounter.monsterHp;}else if(this.encounterKey){this.encounterKey=key;this.seenHp=undefined;const result=state.summary;if(result?.combats===1&&result.defeats===1){this.float(this.hero?.x||350,(this.hero?.y||390)-70,'Recuo','#e69887');this.announce('Voc\u00ea recuou');if(this.hero&&!this.reducedMotion){this.hero.setTint(0xffb6a3);this.tweens.add({targets:this.hero,x:this.hero.x-7,duration:90,yoyo:true,repeat:1,onComplete:()=>{this.hero?.clearTint();}});}}else if(result?.combats===1){this.animate(this.foe,'death');this.float(this.foe.x,this.foe.y-65,'Derrotado','#e2ca94');if(!this.reducedMotion)this.tweens.add({targets:this.foe,alpha:0,y:this.foe.y+9,duration:500});}else{this.announce(result?.combats?`${result.combats} ${result.combats===1?'encontro resolvido':'encontros resolvidos'}`:'Novo encontro');if(!this.reducedMotion)this.tweens.add({targets:this.foe,alpha:0,duration:300});}this.time.delayedCall(520,()=>{if(this.foe?.active&&this.encounterKey===key)this.signature='';});}else this.newEncounter();}if(this.seenHp!==undefined&&c.encounter.monsterHp<this.seenHp){const hit=this.seenHp-c.encounter.monsterHp;if(this.hero){if(this.reducedMotion)this.animate(this.hero,'idle');else this.animate(this.hero,latest.current.skills.some(skill=>skill.classId===c.classId&&c.skills.includes(skill.id)&&skill.damage>0)?'skill':'attack');}if(!this.reducedMotion)this.tweens.add({targets:this.hero,x:405,duration:220,yoyo:true,ease:'Sine.InOut',onComplete:()=>{if(this.hero?.active)this.hero.play(`${this.hero.texture.key}-idle`);}});if(!this.reducedMotion)this.animate(this.foe,'hurt');if(!this.reducedMotion)this.tweens.add({targets:this.foe,x:this.foe.x+5,duration:55,yoyo:true,repeat:1,onComplete:()=>{if(this.foe?.active)this.animate(this.foe,'idle');}});this.float(this.foe.x,this.foe.y-65,`−${hit}`,'#f2d4ad');}this.seenHp=c.encounter.monsterHp;}
    if(this.lastStateTime!==state.serverTime){if(this.lastHeroHp!==undefined&&c.hp!==this.lastHeroHp){const delta=Math.round(c.hp-this.lastHeroHp);this.float(this.hero?.x||350,275,`${delta>0?'+':''}${delta} HP`,delta>0?'#8cd6b3':'#e69887');if(delta>0&&this.hero){const glow=this.add.circle(this.hero.x,this.hero.y-20,28,0x77ddaa,.3);if(this.reducedMotion)glow.destroy();else this.tweens.add({targets:glow,scale:2,alpha:0,duration:600,onComplete:()=>glow.destroy()});}else if(this.hero&&!this.reducedMotion){this.animate(this.hero,'hurt');if(this.foe)this.animate(this.foe,'attack');this.hero.setTint(0xffb6a3);this.tweens.add({targets:this.hero,x:this.hero.x-7,duration:70,yoyo:true,repeat:1,onComplete:()=>{this.hero?.clearTint();}});}}if(state.summary?.combats){this.announce(`${state.summary.combats} encontro${state.summary.combats===1?'':'s'} concluído${state.summary.combats===1?'':'s'}`);if(state.summary.items.length)this.announce('Relíquia encontrada');}this.lastHeroHp=c.hp;this.lastStateTime=state.serverTime;}
    this.hydrated=true;
   }
  }
  const game=new Phaser.Game({type:Phaser.AUTO,parent:host.current!,width:960,height:600,backgroundColor:'#162220',pixelArt:true,antialias:false,scene:WorldScene,scale:{mode:Phaser.Scale.ENVELOP,autoCenter:Phaser.Scale.CENTER_BOTH},audio:{noAudio:true}});
  const visibility=()=>document.hidden?game.loop.sleep():game.loop.wake();document.addEventListener('visibilitychange',visibility);visibility();
  return()=>{document.removeEventListener('visibilitychange',visibility);game.destroy(true);};
 },[]);
 return <div ref={host} className="world-canvas" aria-label="Cena animada do mundo de Cryptidle"/>;
}
