import {useEffect,useRef} from 'react';
import Phaser from 'phaser';
import type {GameState,PlayerPresence,RegionDefinition} from '@cryptidle/shared';
type Props={state:GameState;players:PlayerPresence[];regions:RegionDefinition[]};
export default function World(props:Props){
 const host=useRef<HTMLDivElement>(null), latest=useRef(props);latest.current=props;
 useEffect(()=>{
  class WorldScene extends Phaser.Scene{
   backdrop!:Phaser.GameObjects.Image; actors:Phaser.GameObjects.GameObject[]=[]; signature=''; hero?:Phaser.GameObjects.Sprite; foe?:Phaser.GameObjects.Sprite; lastEncounter=''; lastTime=0; lastHp:number|undefined;
   preload(){for(const k of ['town','forest','crypt','citadel'])this.load.image(k,`/art/${k}.png`);for(const cls of ['warrior','mage','priest'])for(const skin of [0,1])this.load.spritesheet(`${cls}-${skin}`,`/art/${cls}-${skin}.png`,{frameWidth:32,frameHeight:48});for(let i=0;i<10;i++)this.load.spritesheet(`monster-${i}`,`/art/monster-${i}.png`,{frameWidth:32,frameHeight:48});}
   create(){this.backdrop=this.add.image(480,300,'town').setDisplaySize(960,640);for(const key of [...['warrior','mage','priest'].flatMap(c=>[`${c}-0`,`${c}-1`]),...Array.from({length:10},(_,i)=>`monster-${i}`)])for(const [i,action] of ['idle','move','attack','death'].entries())this.anims.create({key:`${key}-${action}`,frames:this.anims.generateFrameNumbers(key,{start:i*3,end:i*3+2}),frameRate:action==='attack'?9:4,repeat:action==='death'?0:-1});this.time.addEvent({delay:2300,loop:true,callback:()=>this.animateFight()});}
   actor(x:number,y:number,key:string,label:string,scale=3){const shadow=this.add.ellipse(x,y+5,65,18,0x05080a,.4);const s=this.add.sprite(x,y,key).setOrigin(.5,.88).setScale(scale).play(`${key}-idle`);const t=this.add.text(x,y+22,label,{fontFamily:'Georgia',fontSize:'15px',color:'#f0e4c9',stroke:'#101718',strokeThickness:4}).setOrigin(.5);this.actors.push(shadow,s,t);return s;}
   float(x:number,y:number,text:string,color:string){const t=this.add.text(x,y,text,{fontSize:'22px',fontFamily:'Georgia',color,stroke:'#111a1e',strokeThickness:4}).setOrigin(.5);this.tweens.add({targets:t,y:y-45,alpha:0,duration:1500,onComplete:()=>t.destroy()});}
   animateFight(){const {state}=latest.current;if(!state.character?.regionId&&state.room?.status!=='running')return;if(!this.hero||!this.foe)return;const h=this.hero,f=this.foe;h.play(`${h.texture.key}-attack`);f.play(`${f.texture.key}-attack`);this.tweens.add({targets:h,x:h.x+18,yoyo:true,duration:180});this.tweens.add({targets:f,alpha:.6,yoyo:true,duration:150});const flash=this.add.arc(f.x-15,f.y-50,32,-50,55,false,0xd9c48b,.5);this.tweens.add({targets:flash,alpha:0,scale:1.6,duration:300,onComplete:()=>flash.destroy()});this.time.delayedCall(600,()=>{if(h.active)h.play(`${h.texture.key}-idle`);if(f.active)f.play(`${f.texture.key}-idle`);});}
   update(){const {state,players,regions}=latest.current,c=state.character;if(!c)return;const boss=state.room?.status==='running',r=regions.findIndex(r=>r.id===c.regionId);const sig=JSON.stringify([c.classId,c.skin,c.regionId,boss,players.filter(p=>!p.regionId).map(p=>[p.id,p.skin]),state.room?.members.map(m=>m.characterId)]);if(sig!==this.signature){this.signature=sig;this.actors.forEach(a=>a.destroy());this.actors=[];this.backdrop.setTexture(boss?'citadel':r<0?'town':['forest','crypt','citadel'][r]||'forest');this.hero=this.actor(r<0&&!boss?470:350,390,`${c.classId}-${c.skin}`,c.name);this.foe=undefined;if(boss){this.foe=this.actor(660,370,'monster-9','O Guardião do Eclipse',5);state.room?.members.filter(m=>m.characterId!==c.id).forEach((m,i)=>this.actor(260+i*90,465,`${m.classId}-${m.skin}`,m.name,2.5));}else if(r>=0){const n=regions[r].monsters.findIndex(m=>m.id===c.encounter?.monsterId);this.foe=this.actor(655,385,`monster-${r*3+Math.max(0,n)}`,regions[r].monsters[Math.max(0,n)]?.name||'Criatura',3.5);}else players.filter(p=>p.id!==c.id&&!p.regionId).slice(0,8).forEach((p,i)=>{const s=this.actor(230+(i%4)*145,310+Math.floor(i/4)*140,`${p.classId}-${p.skin}`,p.name,2.4);s.play(`${s.texture.key}-move`);this.tweens.add({targets:s,x:s.x+15,yoyo:true,repeat:-1,duration:2500+i*200});});}
    if(this.lastTime!==state.serverTime){if(this.lastHp!==undefined&&c.hp!==this.lastHp){const delta=Math.round(c.hp-this.lastHp);this.float(this.hero?.x||350,280,`${delta>0?'+':''}${delta} HP`,delta>0?'#8cd6b3':'#e69887');if(delta>0){const glow=this.add.circle(this.hero?.x||350,355,30,0x77ddaa,.3);this.tweens.add({targets:glow,scale:2,alpha:0,duration:700,onComplete:()=>glow.destroy()});}}if(state.summary?.gold)this.float(480,210,`+${state.summary.gold} gold ? +${state.summary.xp} XP`,'#e0c48a');if(state.summary?.items.length){this.float(500,250,`+${state.summary.items.length} equipamento(s)`,'#c6a1ed');const spark=this.add.star(500,290,5,5,16,0xbb8de0);this.tweens.add({targets:spark,angle:180,alpha:0,y:240,duration:1500,onComplete:()=>spark.destroy()});}this.lastTime=state.serverTime;this.lastHp=c.hp;}const encounter=`${c.huntSeed}:${c.encounter?.monsterId}`;if(this.lastEncounter&&this.lastEncounter!==encounter&&this.foe){this.foe.play(`${this.foe.texture.key}-death`);this.float(this.foe.x,this.foe.y-90,'Novo encontro','#dec287');this.time.delayedCall(800,()=>{this.signature='';});}this.lastEncounter=encounter;
   }
  }
  const game=new Phaser.Game({type:Phaser.AUTO,parent:host.current!,width:960,height:600,backgroundColor:'#162220',pixelArt:true,antialias:false,scene:WorldScene,scale:{mode:Phaser.Scale.ENVELOP,autoCenter:Phaser.Scale.CENTER_BOTH},audio:{noAudio:true}});
  return()=>game.destroy(true);
 },[]);
 return <div ref={host} className="world-canvas" aria-label="Cena animada do mundo de Cryptidle"/>;
}
